version: '3.8'

services:
    api_node:
        container_name: api_list_enzo 
        restart: unless-stopped
        image : enzo13/api_list:1.0 #Version sans utilisateur
        command: npm run start
        working_dir: /usr/src/app
        depends_on:
            - db_mongo
        environment: 
            - API_PORT=$API_PORT
            - MONGO_DB=$MONGO_DB
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
            - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
            - MONGO_PORT=$MONGO_PORT
        networks:
            default:
                aliases:
                    - $API_HOSTNAME
    db_mongo:
        image: mongo
        container_name: mongodb_enzo
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - $MONGO_HOSTNAME
    web_site:
        image: enzo13/angular_list:1.0 
        restart: unless-stopped
        environment: 
            - SITE_HOSTNAME=$SITE_HOSTNAME
            - SITE_PORT=$SITE_PORT
        command: /bin/bash -c "envsubst '$$SITE_HOSTNAME $$SITE_PORT'< /etc/nginx/conf.d/server_web.conf.template > /etc/nginx/conf.d/server_web.conf && nginx -g 'daemon off;'"
        networks:
            default:
                aliases:
                    - $SITE_HOSTNAME

    reverse_proxy:
        image: enzo13/reverseproxy_list:1.0
        restart: unless-stopped
        depends_on:
            - api_node
            - web_site
        container_name: reverse_proxy_enzo
        working_dir: /etc/nginx/conf.d
        environment:
            - API_HOSTNAME=$API_HOSTNAME
            - API_PORT=$API_PORT
            - SITE_HOSTNAME=$SITE_HOSTNAME
            - SITE_PORT=$SITE_PORT
            - PROXY_HOSTNAME=$PROXY_HOSTNAME

        ports:
            - $HOST_PORT:80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/reverse_proxy.conf.template > /etc/nginx/conf.d/reverse_proxy.conf && nginx -g 'daemon off;'"
