version: '3.8'

services:
    api_node:
        container_name: api_immo
        restart: unless-stopped
        image : node:14.9
        command: npm run start
        volumes:
            - ./api_node:/usr/src/app
        working_dir: /usr/src/app
        depends_on:
            - db_mongo
        environment: 
            - API_PORT=$API_PORT
            - MONGO_DB=$MONGO_DB
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
            - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
            - MONGO_PORT=$MONGO_PORT
        networks:
            default:
                aliases:
                    - $API_HOSTNAME
    db_mongo:
        image: mongo:4
        container_name: mongodb
        restart: unless-stopped
        environment:
            - MONGO_INITDB_DATABASE=$MONGO_DB
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
            - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
            - MONGO_DB=$MONGO_DB
        volumes:
            - mongoCourse:/data/db
            - ./bdd/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            - ./bdd/.dbshell:/home/mongodb/.dbshell
        networks:
            default:
                aliases:
                    - $MONGO_HOSTNAME
    reverse_proxy:
        image: nginx:1.18
        restart: unless-stopped
        container_name: reverse_proxy
        depends_on:
            - api_node
        volumes:
            - ./reverse_proxy:/etc/nginx/conf.d
        working_dir: /etc/nginx/conf.d
        environment:
            - API_HOSTNAME=$API_HOSTNAME
            - API_PORT=$API_PORT
            - SITE_HOSTNAME=$SITE_HOSTNAME
            - SITE_PORT=$SITE_PORT
            - PROXY_HOSTNAME=$PROXY_HOSTNAME

        ports:
            - $HOST_PORT:80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/reverse_proxy.conf.template > /etc/nginx/conf.d/reverse_proxy.conf && nginx -g 'daemon off;'"

volumes:
    mongoCourse:
        external: true